import localFont from "next/font/local";
import "./globals.css";
import LenisSmoothScroll from "@/Animation/Lenis";


const DMMono = localFont({
  src: [
    { path: "./fonts/DMMono-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/DMMono-Regular.woff2", weight: "400", style: "normal" },

   
  ],
  variable: "--font-DMMono",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
});

const faRegular = localFont({
  src: [
    { path: "./fonts/fa-regular-400.woff2", weight: "400", style: "normal" },
    { path: "./fonts/fa-solid-900.woff2", weight: "900", style: "normal" },
   
  ],
  variable: "--font-faRegular",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
});

const Robert = localFont({
  src: [
    { path: "./fonts/Roobert-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/Roobert-Medium.woff2",  weight: "500", style: "normal" },
   
  ],
  variable: "--font-Robert",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
});

export const metadata = {
  title: "Relats | Top Tier Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <LenisSmoothScroll />

      <body
        className={`${Robert.variable} ${faRegular.variable} ${DMMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
